dist: xenial
language: go

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+.*$/
  - /^release-\d+.\d+.*$/
  - lighthouse-0.3.0

git:
  depth: false

jobs:
  include:
  - env: CMD="make test validate"
  - env: CMD="make e2e deploytool=operator"
         RELEASE=true
  - env: CMD="make e2e deploytool=helm"

install:
  - sudo apt-get install moreutils # make ts available

services:
  - docker
before_script:
  - CHANGED_FILES_PR=$(git diff --name-only HEAD $(git merge-base HEAD $TRAVIS_BRANCH))
script:
  - set -o pipefail;
    $CMD 2>&1 | ts '[%H:%M:%.S]' -s
after_success:
  - if [[ "${CHANGED_FILES_PR[@]}" =~ "scripts/kind-e2e/e2e.sh" ]]; then
      echo "scripts/kind-e2e/e2e.sh was modified, testing recurring run on already deployed infrastructure.";
      set -o pipefail;
      $CMD 2>&1 | ts '[%H:%M:%.S]' -s;
    fi
  - echo "Testing cleaning up clusters";
    set -o pipefail;
    make cleanup 2>&1 | ts '[%H:%M:%.S]' -s
deploy:
  - provider: script
    script: bash scripts/release
    on:
      branch: master
      condition: $RELEASE = true
  - provider: script
    script: bash scripts/release
    on:
      branch: /^release-\d+.\d+.*$/

  - provider: script
    script: bash scripts/release $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
      condition: $RELEASE = true
